version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend/:/code
    ports:
      - 81:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - 80:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - backend
