version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend/:/code
    ports:
      - 80:5000
    #environment:
