version: '3.7'

services:
  redis:
    image: redis
    container_name: cache
    volumes:
      - ./tmp:/data
    ports:
      - 6379:6379

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend/:/code
    ports:
      - 81:5000
    links:
      - redis
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/code
      - ./frontend/node_modules:/code/node_modules
    ports:
      - 80:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    links:
      - backend
